#!/bin/bash

export ROS_IP=192.168.42.67
export ROS_MASTER_URI=http://192.168.42.71:11311

source /sysgen/ros_workspaces/neurobots_catkin_ws/devel/setup.bash --extend
source /sysgen/ros_workspaces/perception_ws/devel/setup.bash --extend

exec "$@"
