#!/bin/bash


export ROS_IP=192.168.42.67
export ROS_MASTER_URI=http://192.168.42.71:11311

roslaunch extrinsic_camera_calibration simtrack_calibration.launch calibration_camera_name:=$1 sync_queue_size:=$2

