#!/bin/bash

camera="$1"

devices=`lsusb | grep ASUS | cut -d' ' -f4 | sed s/://g`

for device in $devices; do
	log=`lsusb -s $device -vvv`
	total_length=`echo $log | grep -o "wTotalLength [0-9]*" | head -1 | cut -d' ' -f2`
	echo $total_length
 	device_without_zero=$(echo $device | sed 's/^0*//')

	#face camera
	if [ $camera == "face" ] && [ $total_length -eq 206 ]; then
		echo "Found face camera on device" $device
		roslaunch neurobots_launch face_camera.launch device_id:=1/$device_without_zero
		break
	fi
	if [ $camera == "omnirob" ] && [ $total_length -eq 183 ]; then
		echo "Found omnirob camera on device" $device
		roslaunch neurobots_launch omnirob_camera.launch device_id:=1/$device_without_zero
		break
	fi
done


