# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  iiwa_1_joint:
    has_velocity_limits: true
    max_velocity: 0.1963
    has_acceleration_limits: false
    max_acceleration: 0
  iiwa_2_joint:
    has_velocity_limits: true
    max_velocity: 0.1963
    has_acceleration_limits: false
    max_acceleration: 0
  iiwa_3_joint:
    has_velocity_limits: true
    max_velocity: 0.1963
    has_acceleration_limits: false
    max_acceleration: 0
  iiwa_4_joint:
    has_velocity_limits: true
    max_velocity: 0.1963
    has_acceleration_limits: false
    max_acceleration: 0
  iiwa_5_joint:
    has_velocity_limits: true
    max_velocity: 0.1963
    has_acceleration_limits: false
    max_acceleration: 0
  iiwa_6_joint:
    has_velocity_limits: true
    max_velocity: 0.1963
    has_acceleration_limits: false
    max_acceleration: 0
  iiwa_7_joint:
    has_velocity_limits: true
    max_velocity: 0.1963
    has_acceleration_limits: false
    max_acceleration: 0
