# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
# Joint Position Trajectory Controllers -----------------------
position_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - lbr_1_joint
    - lbr_2_joint
    - lbr_3_joint
    - lbr_4_joint
    - lbr_5_joint
    - lbr_6_joint
    - lbr_7_joint
    
# Joint Velocity Trajectory Controllers -----------------------
velocity_trajectory_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - lbr_1_joint
    - lbr_2_joint
    - lbr_3_joint
    - lbr_4_joint
    - lbr_5_joint
    - lbr_6_joint
    - lbr_7_joint
  gains: # Needed to map position+velocity commands to an effort command
    lbr_1_joint: {p: 10.0,  i: 0.1, d: 1.0, i_clamp: 1, i_clamp_min: 0, i_clamp_max: 0}
    lbr_2_joint: {p: 10.0,  i: 0.1, d: 1.0, i_clamp: 1, i_clamp_min: 0, i_clamp_max: 0}
    lbr_3_joint: {p: 10.0,  i: 0.1, d: 1.0, i_clamp: 1, i_clamp_min: 0, i_clamp_max: 0}
    lbr_4_joint: {p: 10.0,  i: 0.1, d: 1.0, i_clamp: 1, i_clamp_min: 0, i_clamp_max: 0}
    lbr_5_joint: {p: 10.0,  i: 0.1, d: 1.0, i_clamp: 1, i_clamp_min: 0, i_clamp_max: 0}
    lbr_6_joint: {p: 10.0,  i: 0.1, d: 1.0, i_clamp: 1, i_clamp_min: 0, i_clamp_max: 0}
    lbr_7_joint: {p: 10.0,  i: 0.1, d: 1.0, i_clamp: 1, i_clamp_min: 0, i_clamp_max: 0}
  constraints:
    goal_time: 0.005 
    stopped_velocity_tolerance: 0.01
    lbr_1_joint:
      trajectory: 0.0
      goal: 0.01 
    lbr_2_joint:
      trajectory: 0.0
      goal: 0.01
    lbr_3_joint:
      trajectory: 0.0
      goal: 0.01 
    lbr_4_joint:
      trajectory: 0.0
      goal: 0.01
    lbr_5_joint:
      trajectory: 0.0
      goal: 0.01 
    lbr_6_joint:
      trajectory: 0.0
      goal: 0.01 
    lbr_7_joint:
      trajectory: 0.0
      goal: 0.01 
  
 # Joint Torque Controllers -----------------------
joint_torque_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - lbr_1_joint
    - lbr_2_joint
    - lbr_3_joint
    - lbr_4_joint
    - lbr_5_joint
    - lbr_6_joint
    - lbr_7_joint
  gains: # Needed to map position+velocity commands to an effort command
    lbr_1_joint: {p: 10.0,  i: 0.1, d: 1.0, i_clamp: 1, i_clamp_min: 0, i_clamp_max: 0}
    lbr_2_joint: {p: 10.0,  i: 0.1, d: 1.0, i_clamp: 1, i_clamp_min: 0, i_clamp_max: 0}
    lbr_3_joint: {p: 10.0,  i: 0.1, d: 1.0, i_clamp: 1, i_clamp_min: 0, i_clamp_max: 0}
    lbr_4_joint: {p: 10.0,  i: 0.1, d: 1.0, i_clamp: 1, i_clamp_min: 0, i_clamp_max: 0}
    lbr_5_joint: {p: 10.0,  i: 0.1, d: 1.0, i_clamp: 1, i_clamp_min: 0, i_clamp_max: 0}
    lbr_6_joint: {p: 10.0,  i: 0.1, d: 1.0, i_clamp: 1, i_clamp_min: 0, i_clamp_max: 0}
    lbr_7_joint: {p: 10.0,  i: 0.1, d: 1.0, i_clamp: 1, i_clamp_min: 0, i_clamp_max: 0}
  constraints:
    goal_time: 0.005 
    stopped_velocity_tolerance: 0.01
    lbr_1_joint:
      trajectory: 0.0
      goal: 0.01 
    lbr_2_joint:
      trajectory: 0.0
      goal: 0.01
    lbr_3_joint:
      trajectory: 0.0
      goal: 0.01 
    lbr_4_joint:
      trajectory: 0.0
      goal: 0.01
    lbr_5_joint:
      trajectory: 0.0
      goal: 0.01 
    lbr_6_joint:
      trajectory: 0.0
      goal: 0.01 
    lbr_7_joint:
      trajectory: 0.0
      goal: 0.01 