controller_list:
  - name: fake_iiwa_controller
    joints:
      - iiwa_1_joint
      - iiwa_2_joint
      - iiwa_3_joint
      - iiwa_4_joint
      - iiwa_5_joint
      - iiwa_6_joint
      - iiwa_7_joint