(define (problem scenario_gen_4_6_4_5_7)
 (:domain neurobots-simgen)

 (:objects
   kitchen living-room pantry bathroom garden - room
   omnirob - robot
   me friend - human
   flower-bed - flowerbed
   shelf1 shelf2 shelf3 - shelf
   dining-table couch-table - table
   ballon wwineglas cylinder beerstein - shape
   water lemonade apple-juice orange-juice red-wine white-wine beer - content
   red white yellow blue green - color
   left right - alignment
   c0 c1 c2 c3 - cup
   g0 g1 g2 g3 g4 g5 - glass
   b0 b1 b2 b3 - bottle
   v0 v1 v2 v3 v4 - vase
   f0 f1 - tulip
   f2 f3 - sunflower
   f4 f5 f6 - rose
 )

 (:init
   (connected kitchen kitchen)
   (connected living-room living-room)
   (connected pantry pantry)
   (connected bathroom bathroom)
   (connected garden garden)
   (connected kitchen pantry)
   (connected pantry kitchen)
   (connected kitchen living-room)
   (connected living-room kitchen)
   (connected living-room garden)
   (connected garden living-room)
   (connected living-room bathroom)
   (connected bathroom living-room)
   (= (in shelf1) pantry)
   (= (aligned shelf1) left)
   (= (in shelf2) pantry)
   (= (aligned shelf2) right)
   (= (in shelf3) bathroom)
   (= (aligned shelf3) left)
   (= (in flower-bed) garden)
   (= (in dining-table) kitchen)
   (= (in couch-table) living-room)
   (= (in me) living-room)
   (= (in friend) living-room)
   (= (in omnirob) kitchen)
   (= (at omnirob) nowhere)
   (mobile omnirob)
   (arm-empty omnirob)
   (= (position c0) shelf3)
   (is-open c0)
   (= (contains c0) empty)
   (= (colored c0) yellow)
   (= (position c1) couch-table)
   (is-open c1)
   (= (contains c1) empty)
   (= (colored c1) green)
   (= (position c2) dining-table)
   (is-open c2)
   (= (contains c2) empty)
   (= (colored c2) white)
   (= (position c3) shelf3)
   (is-open c3)
   (= (contains c3) empty)
   (= (colored c3) green)
   (= (position g0) shelf2)
   (is-open g0)
   (= (contains g0) empty)
   (= (shaped g0) cylinder)
   (= (position g1) shelf1)
   (is-open g1)
   (= (contains g1) water)
   (= (shaped g1) cylinder)
   (= (position g2) dining-table)
   (is-open g2)
   (= (contains g2) empty)
   (= (shaped g2) wwineglas)
   (= (position g3) shelf3)
   (is-open g3)
   (= (contains g3) water)
   (= (shaped g3) wwineglas)
   (= (position g4) shelf2)
   (is-open g4)
   (= (contains g4) empty)
   (= (shaped g4) cylinder)
   (= (position g5) couch-table)
   (is-open g5)
   (= (contains g5) water)
   (= (shaped g5) cylinder)
   (= (position b0) shelf2)
   (= (contains b0) red-wine)
   (= (position b1) couch-table)
   (= (contains b1) white-wine)
   (= (position b2) shelf3)
   (= (contains b2) white-wine)
   (= (position b3) shelf1)
   (= (contains b3) beer)
   (= (position v0) shelf2)
   (= (contains v0) empty)
   (= (colored v0) yellow)
   (= (position v1) shelf3)
   (= (contains v1) f3)
   (= (colored v1) green)
   (= (position v2) shelf1)
   (= (contains v2) empty)
   (= (colored v2) white)
   (= (position v3) shelf2)
   (= (contains v3) empty)
   (= (colored v3) red)
   (= (position v4) couch-table)
   (= (contains v4) empty)
   (= (colored v4) green)
   (= (colored f0) yellow)
   (= (position f0) flower-bed)
   (= (colored f1) red)
   (= (position f1) flower-bed)
   (= (colored f2) yellow)
   (= (position f2) flower-bed)
   (= (colored f3) yellow)
   (= (position f3) v1)
   (= (colored f4) white)
   (= (position f4) flower-bed)
   (= (colored f5) white)
   (= (position f5) flower-bed)
   (= (colored f6) red)
   (= (position f6) flower-bed)
 )

 (:goal (and)
)
)