sensors:
- sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /vrep/depth/cloud
  max_range: 3.0
  point_subsample: 1
  padding_offset: 0.05
  padding_scale: 1.0
  filtered_cloud_topic: output_cloud
